
import java.util.Arrays;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Emiliano Mendoza
 */
public class IngresoAsignatura extends javax.swing.JPanel {
    
    public static String materia[] = new String[3]; 
    public static int cantMaterias = 0;
    
    public String[] getMaterias(){
        return materia;
    }
    
    /**
     * Creates new form ingresoAsignatura
     */
    public IngresoAsignatura() {
        initComponents();
        msjLimiteAsig.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        msjLimiteAsig = new javax.swing.JLabel();
        btnOkAsignaturas = new javax.swing.JButton();
        inputAsignatura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(847, 659));
        setPreferredSize(new java.awt.Dimension(847, 659));
        setLayout(new java.awt.GridBagLayout());

        msjLimiteAsig.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        msjLimiteAsig.setForeground(new java.awt.Color(255, 51, 51));
        msjLimiteAsig.setText("Ha alcanzado el limite de materias permitido.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 130, 0, 0);
        add(msjLimiteAsig, gridBagConstraints);

        btnOkAsignaturas.setLabel("Agregar");
        btnOkAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkAsignaturasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 130, 174, 0);
        add(btnOkAsignaturas, gridBagConstraints);

        inputAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAsignaturaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 130, 0, 131);
        add(inputAsignatura, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese las asignaturas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(174, 130, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inputAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAsignaturaActionPerformed
        // TODO add your handling code here:
        //esto debe ser el cuadro donde pones el texto i guess
    }//GEN-LAST:event_inputAsignaturaActionPerformed

    private void btnOkAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkAsignaturasActionPerformed
        if(cantMaterias < 3){ //si la cantidad de materias es menor a 3, guarda la 
            materia[cantMaterias] =  inputAsignatura.getText();//materia en el array materia
            System.out.println(Arrays.toString(materia));
            inputAsignatura.setText("");
            cantMaterias++;
        }else{
            msjLimiteAsig.setVisible(true); //sino pone el error
        }
    }//GEN-LAST:event_btnOkAsignaturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkAsignaturas;
    private javax.swing.JTextField inputAsignatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel msjLimiteAsig;
    // End of variables declaration//GEN-END:variables
}

