
import java.util.Arrays;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Emiliano Mendoza
 */
public class IngresoEstudiante extends javax.swing.JPanel {

    public static String alumnos[] = new String[5];
    public static int cantAlumnos = 0;
    
    
    /**
     * Creates new form ingresoEstudiante
     */
    public IngresoEstudiante() {
        initComponents();
        msjLimiteEstud.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel5 = new javax.swing.JLabel();
        btnAgregarEstudiante = new javax.swing.JButton();
        inputEstudiantes = new javax.swing.JTextField();
        msjLimiteEstud = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(847, 659));
        setPreferredSize(new java.awt.Dimension(847, 659));
        setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jLabel5.setText("Ingrese los nombres de los estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(355, 244, 0, 245);
        add(jLabel5, gridBagConstraints);

        btnAgregarEstudiante.setLabel("Agregar");
        btnAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudianteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 244, 356, 0);
        add(btnAgregarEstudiante, gridBagConstraints);

        inputEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEstudiantesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 244, 0, 245);
        add(inputEstudiantes, gridBagConstraints);

        msjLimiteEstud.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        msjLimiteEstud.setForeground(new java.awt.Color(255, 51, 51));
        msjLimiteEstud.setText("Ha alcanzado el limite de alumnos.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 244, 0, 0);
        add(msjLimiteEstud, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inputEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEstudiantesActionPerformed

    private void btnAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudianteActionPerformed
        if(cantAlumnos < 5){
            alumnos[cantAlumnos] =  inputEstudiantes.getText();
            System.out.println(Arrays.toString(alumnos));
            inputEstudiantes.setText("");
            cantAlumnos++;
        }else{
            msjLimiteEstud.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JTextField inputEstudiantes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel msjLimiteEstud;
    // End of variables declaration//GEN-END:variables
}
